---
format: html
---

### Education

2016 – 2021 PhD in History, University of Cambridge, Faculty of History

2013 – 2015 MA in Philosophical Sciences, Collegio Superiore, University of Bologna

2010 - 2013 BA in Philosophy, University of Bologna

### Academic positions

2025 – *in progress* Tenure-track Assistant Professor (RTT) in Economic History, Sant’Anna School of Advanced Studies, Institute of Economics, Pisa

2023 - 2025 Max Weber Fellow in History, European University Institute, Faculty of History, Fiesole

2021 - 2023 Postdoctoral Fellow, Sant’Anna School of Advanced Studies, Institute of Economics, Pisa

### Grants

2025 - *in progress* Italian Ministry of University and Research (Ministero dell’università e della ricerca), Fondo Italiano per la Scienza (FIS). Award of FIS Starting Grant as PI of the project Working Knowledge: the emergence of practitioners in late medieval and early modern Europe (<a href="Projects.html">WorKnow</a>).

<br>

Want to know more? You can find my full CV <a href="files/CV_Raffaele_Danna.pdf" target="_blank">here</a>
