---
title: ""
---

## Working Knowledge: The Emergence of Practitioners in Late Medieval and Early Modern Europe (WorKnow)

#### WorKnow aims to reconsider the co-emergence and co-evolution of the “Scientific Revolution” and the “Industrial Revolution”

#### **Funding**

The project supported by a Starting Grant awarded by the Italian Fund for Science (Fondo Italiano per la Scienza) of the Italian Ministery for Research.

FIS grants promote the development of fundamental research, following the model of the European Research Council (ERC).

#### **The idea**

One of the biggest questions in early modern history is explaining how Europe developed “scientific” and “industrial” revolutions that allowed it to diverge from the rest of the world, eventually leading to the period of European global domination. While there are extensive literatures in the history of science and in economic history that seek to explain how the respective “revolutions” came about, attempts to connect economic and scientific change in this period are relatively limited. However, both historians of science and economic historians are converging in their research interests, as the two fields are increasingly stressing the important role of an emergent class of practitioners in promoting both theoretical and economic change in early modern Europe. WorKnow stems from this important convergence of economic history and the history of science, and aims to contribute to both fields.

**Historians of science** have investigated the sociological origins of the “scientific revolution” for a long time (Zilsel 1942; Rossi 1970). This stream of studies has documented the important role not of major scientists, but of humbler figures such as artisans and other practitioners, in making possible new alliances between natural philosophy, mathematisation, and experimentation. These studies have challenged the narratives of scientific discoveries focused on individual scientists, and have contributed to understanding the “scientific revolution” as a collective and socially embedded process (Shapin and Schaffer 1985; Kassell 2005; Long 2015). Practical texts provide direct evidence of how, starting from the late medieval period, new bodies of “practical knowledge” emerged from the world of artisans and practitioners, setting in motion broader changes in the social circulation of knowledge (P. H. Smith 2004; Roberts, Schaffer, and Dear 2007; Long 2011; Fox 2009; Bertucci 2017; P. H. Smith 2022).

**Economic historians**, together with exploring environmental, technological, institutional, and macroeconomic factors, have recently revisited the thesis that a key contribution to the “industrial revolution” came from the world of practitioners (Cipolla 1969; Berg 1994). This literature has stressed the essential role in this period of deep economic change of the knowledge promoted by practically minded enlightenment intellectuals and by humbler figures, such as artisans and other practitioners (Mokyr 2002; 2005; 2017; Berg 2007, 200; Kelly, Mokyr, and Ó Gráda 2014; Cinnirella, Hornung, and Koschnick 2022). Kelly and Ó Gráda (2022) have shown how practical mathematics is a particularly significant field to explore the connections between economic and scientific change in this crucial period.

**However**, while some of these practitioners have received much scholarly attention (Kassell 2005; Biagioli 2006; Long et al. 2009; P. H. Smith 2022), their emergence as a long-run and incremental phenomenon is still understudied. Historians of science have mainly focused on individual practitioners rather than studying their emergence as a social phenomenon, and have not sought to reconstruct its quantitative features and its dynamics. At the same time, economic historians have not fully taken into account the epistemological relevance of the emergence of practical knowledge.

**WorKnow aims to bridge this gap** by creating a dialogue between these streams of literature and by reconstructing in unprecedented detail the emergence of practitioners and of practical knowledge in early modern Europe.

#### **Within this project**

[Special Issue](https://www.museogalileo.it/it/attivita/news/call-for-abstracts-galilaeana-knowledge-in-use.html) of *Galilaeana – Studies in Renaissance and Early Modern Science*. Theme: “Knowledge in Use. Practices and Practitioners in the Renaissance and Early Modern Period (14th-17th centuries)”. Expected publication: October 2026. (with Francesco Brusori)

<br>

#### **References**

Berg, Maxine. 1994. *The Age of Manufactures, 1700-1820: Industry, Innovation and Work in Britain*. 2nd ed. London: Routledge.

———. 2007. ‘The Genesis of “Useful Knowledge”’. *History of Science* 45 (2): 123–33.

Bertucci, Paola. 2017. *Artisanal Enlightenment: Science and the Mechanical Arts in Old Regime France*. New Haven ; London: Yale University Press.

Biagioli, Mario. 2006. *Galileo’s Instruments of Credit: Telescopes, Images, Secrecy*. Chicago ; London: University of Chicago Press.

Cinnirella, Francesco, Erik Hornung, and Julius Koschnick. 2022. ‘Flow of Ideas: Economic Societies and the Rise of Useful Knowledge’. *SSRN Scholarly Paper*.

Cipolla, Carlo M. 1969. *Literacy and Development in the West*. Harmondsworth: Penguin.

Fox, Celina. 2009. *The Arts of Industry in the Age of Enlightenment*. New Haven, Conn. ; London: Yale University Press.

Kassell, Lauren. 2005. *Medicine and Magic in Elizabethan London: Simon Forman: Astrologer, Alchemist, and Physician*. Oxford: Clarendon Press.

Kelly, Morgan, Joel Mokyr, and Cormac Ó Gráda. 2014. ‘Precocious Albion: A New Interpretation of the British Industrial Revolution’. *Annual Review of Economics* 6 (1): 363–89.

Kelly, Morgan, and Cormac Ó Gráda. 2022. ‘Connecting the Scientific and Industrial Revolutions: The Role of Practical Mathematics’. *The Journal of Economic History* 82 (3): 841–73.

Long, Pamela O. 2011. *Artisan/Practitioners and the Rise of the New Sciences, 1400-1600*. Corvallis, OR: Oregon State University Press.

———. 2015. ‘Trading Zones in Early Modern Europe’. *Isis* 106 (4): 840–47.

Long, Pamela O., David McGee, Alan M. Stahl, and Franco Rossi, eds. 2009. *The Book of Michael of Rhodes: A Fifteenth-Century Maritime Manuscript*. 3 vols. Cambridge, MA ; London: MIT Press.

Mokyr, Joel. 2002. *The Gifts of Athena: Historical Origins of the Knowledge Economy*. Princeton, N.J. ; Oxford: Princeton University Press.

———. 2005. ‘The Intellectual Origins of Modern Economic Growth’. *The Journal of Economic History* 65 (2): 285–351.

———. 2017. *A Culture of Growth: The Origins of the Modern Economy*. Princeton, N.J.: Princeton University Press.

Roberts, Lissa, Simon Schaffer, and Peter Dear, eds. 2007. *The Mindful Hand: Inquiry and Invention from the Late Renaissance to Early Industrialisation*. Amsterdam: Koninkliijke Nederlandse Akademie van Wetenschappen.

Rossi, Paolo. 1970. *Philosophy, Technology, and the Arts in the Early Modern Era*. New York: Harper & Row.

Shapin, Steven, and Simon Schaffer. 1985. *Leviathan and the Air-Pump: Hobbes, Boyle, and the Experimental Life*. Princeton, N.J.: Princeton University Press.

Smith, Pamela H. 2004. *The Body of the Artisan Art and Experience in the Scientific Revolution*. Chicago ; London: University of Chicago Press.

———. 2022. *From Lived Experience to the Written Word: Reconstructing Practical Knowledge in the Early Modern World*. Chicago: University of Chicago Press.

Zilsel, Edgar. 1942. ‘The Sociological Roots of Science’. *American Journal of Sociology* 47 (4): 544–62.
